#!/usr/bin/env python
import miniupnpc
u = miniupnpc.UPnP()
u.discoverdelay=200;u.discover();u.selectigd()

import sys
u.addportmapping('28015','UDP',u.lanaddr,’28015,'upnp-add-port '+str(’28015’),'')

u.addportmapping('28015','TCP',u.lanaddr,’28015,'upnp-add-port '+str(’28015’),'')

u.addportmapping('28016','TCP',u.lanaddr,’28016,'upnp-add-port '+str(’28016’),'')

u.addportmapping('8080,'TCP',u.lanaddr,’8080,'upnp-add-port '+str(’8080’),'')