#!/usr/bin/env python
import miniupnpc
u = miniupnpc.UPnP()
u.discoverdelay=200;u.discover();u.selectigd()

import sys; portNo = int(sys.argv[-1])
u.deleteportmapping(portNo,'UDP')
u.deleteportmapping(portNo,'TCP')
